debug=true

[server]
port=8000

[cache]
enable=false

[database]
name="{{ config.database.name }}"
user="{{ config.database.user }}"
password="{{ config.database.password }}"
port={{ config.database.port }}
host="{{ config.database.host }}"

[prometheus]
username="change_this"
password="change_this"

