imports:
- { resource: services.yml }
- { resource: packages.yml }

parameters:

  application:
    name:         CrudGenerator
    slug:         crud-generator
    version:      0.0.1
    description:  "Genera Aplicaciones simples"
